export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type FilmVisibility = 'public' | 'unlisted' | 'private' | 'draft';
export type ContentRating = 'G' | 'PG' | 'T' | 'M';
export type CreatorRole = 'director' | 'writer' | 'animator' | 'producer' | 'sound_designer' | 'asset_creator' | 'voice_actor';
export type AssetCategory = 'character' | 'prop' | 'environment' | 'sprite' | 'animation_clip' | 'sound_pack' | 'template';
export type AssetPricing = 'free' | 'purchase' | 'rental' | 'royalty';
export type NotificationType = 'donation_received' | 'comment_received' | 'like_received' | 'follow_received' | 'collab_invite' | 'collab_accepted' | 'asset_purchased' | 'asset_review' | 'fund_payout' | 'film_published' | 'episode_released';

export interface Profile {
  id: string;
  display_name: string;
  username: string;
  avatar_url: string | null;
  bio: string | null;
  website: string | null;
  wallet_address: string | null;
  total_films: number | null;
  total_views: string | null;
  total_earned_wei: string | null;
  follower_count: number | null;
  following_count: number | null;
  creator_weight: number | null;
  preferred_language: string | null;
  preferred_role: string | null;
  created_at: string | null;
  updated_at: string | null;
}

export interface ProfileInsert {
  id: string;
  display_name: string;
  username: string;
  avatar_url?: string | null;
  bio?: string | null;
  website?: string | null;
  wallet_address?: string | null;
  preferred_language?: string | null;
  preferred_role?: string | null;
  // Generated/Defaulted fields can be omitted or optional
  total_films?: number | null;
  total_views?: string | null;
  total_earned_wei?: string | null;
  follower_count?: number | null;
  following_count?: number | null;
  creator_weight?: number | null;
  created_at?: string | null;
  updated_at?: string | null;
}

export interface ProfileUpdate extends Partial<ProfileInsert> {}

export interface Series {
  id: string;
  owner_id: string;
  title: string;
  description: string | null;
  thumbnail_url: string | null;
  slug: string;
  genre: string | null;
  tags: string[] | null;
  episode_count: number | null;
  subscriber_count: number | null;
  created_at: string | null;
  updated_at: string | null;
}

export interface SeriesInsert {
  id?: string;
  owner_id: string;
  title: string;
  slug: string;
  description?: string | null;
  thumbnail_url?: string | null;
  genre?: string | null;
  tags?: string[] | null;
  episode_count?: number | null;
  subscriber_count?: number | null;
  created_at?: string | null;
  updated_at?: string | null;
}

export interface SeriesUpdate extends Partial<SeriesInsert> {}

export interface Film {
  id: string;
  owner_id: string;
  title: string;
  description: string | null;
  slug: string;
  thumbnail_url: string | null;
  video_url: string | null;
  project_json: Record<string, unknown> | null;
  duration_seconds: number | null;
  rating: ContentRating | null;
  visibility: FilmVisibility | null;
  tags: string[] | null;
  genre: string | null;
  language: string | null;
  series_id: string | null;
  episode_number: number | null;
  season_number: number | null;
  view_count: string | null;
  like_count: number | null;
  comment_count: number | null;
  donation_total_wei: string | null;
  avg_retention_pct: number | null;
  chain_film_id: string | null;
  published_at: string | null;
  created_at: string | null;
  updated_at: string | null;
  fts: string | null;
}

export interface FilmInsert {
  id?: string;
  owner_id: string;
  title: string;
  slug?: string; // Generated by trigger if empty
  description?: string | null;
  thumbnail_url?: string | null;
  video_url?: string | null;
  project_json?: Record<string, unknown> | null;
  duration_seconds?: number | null;
  rating?: ContentRating | null;
  visibility?: FilmVisibility | null;
  tags?: string[] | null;
  genre?: string | null;
  language?: string | null;
  series_id?: string | null;
  episode_number?: number | null;
  season_number?: number | null;
  chain_film_id?: string | null;
  published_at?: string | null;
  // Generated/Defaulted
  view_count?: string | null;
  like_count?: number | null;
  comment_count?: number | null;
  donation_total_wei?: string | null;
  avg_retention_pct?: number | null;
  created_at?: string | null;
  updated_at?: string | null;
  fts?: string | null;
}

export interface FilmUpdate extends Partial<FilmInsert> {}

export interface FilmCreator {
  film_id: string;
  user_id: string;
  role: CreatorRole;
  revenue_share_bps: number;
  invited_at: string | null;
  accepted_at: string | null;
}

export interface FilmCreatorInsert {
  film_id: string;
  user_id: string;
  role: CreatorRole;
  revenue_share_bps?: number;
  invited_at?: string | null;
  accepted_at?: string | null;
}

export interface FilmCreatorUpdate extends Partial<FilmCreatorInsert> {}

export interface View {
  id: string;
  film_id: string;
  user_id: string | null;
  session_id: string;
  watched_seconds: number | null;
  total_seconds: number;
  retention_pct: number | null;
  source: string | null;
  device: string | null;
  country: string | null;
  created_at: string | null;
}

export interface ViewInsert {
  id?: string;
  film_id: string;
  user_id?: string | null;
  session_id: string;
  watched_seconds?: number | null;
  total_seconds: number;
  source?: string | null;
  device?: string | null;
  country?: string | null;
  created_at?: string | null;
}

export interface ViewUpdate extends Partial<ViewInsert> {}

export interface Donation {
  id: string;
  donor_id: string | null;
  film_id: string;
  amount_wei: string;
  amount_usd: number | null;
  currency: string | null;
  tx_hash: string;
  chain: string | null;
  block_number: string | null;
  creator_amount_wei: string;
  fund_amount_wei: string;
  platform_amount_wei: string;
  stripe_payment_id: string | null;
  is_fiat: boolean | null;
  created_at: string | null;
}

export interface DonationInsert {
  id?: string;
  donor_id?: string | null;
  film_id: string;
  amount_wei: string;
  amount_usd?: number | null;
  currency?: string | null;
  tx_hash: string;
  chain?: string | null;
  block_number?: string | null;
  creator_amount_wei: string;
  fund_amount_wei: string;
  platform_amount_wei: string;
  stripe_payment_id?: string | null;
  is_fiat?: boolean | null;
  created_at?: string | null;
}

export interface DonationUpdate extends Partial<DonationInsert> {}

export interface Comment {
  id: string;
  film_id: string;
  user_id: string;
  parent_id: string | null;
  body: string;
  is_edited: boolean | null;
  is_hidden: boolean | null;
  like_count: number | null;
  reply_count: number | null;
  created_at: string | null;
  updated_at: string | null;
}

export interface CommentInsert {
  id?: string;
  film_id: string;
  user_id: string;
  parent_id?: string | null;
  body: string;
  is_edited?: boolean | null;
  is_hidden?: boolean | null;
  like_count?: number | null;
  reply_count?: number | null;
  created_at?: string | null;
  updated_at?: string | null;
}

export interface CommentUpdate extends Partial<CommentInsert> {}

export interface Like {
  film_id: string;
  user_id: string;
  created_at: string | null;
}

export interface LikeInsert {
  film_id: string;
  user_id: string;
  created_at?: string | null;
}

export interface LikeUpdate extends Partial<LikeInsert> {}

export interface Follow {
  follower_id: string;
  following_id: string;
  created_at: string | null;
}

export interface FollowInsert {
  follower_id: string;
  following_id: string;
  created_at?: string | null;
}

export interface FollowUpdate extends Partial<FollowInsert> {}

export interface Asset {
  id: string;
  creator_id: string;
  name: string;
  description: string | null;
  category: AssetCategory;
  tags: string[] | null;
  file_url: string;
  preview_url: string | null;
  thumbnail_url: string | null;
  file_size_bytes: string | null;
  polygon_count: number | null;
  file_format: string | null;
  pricing_model: AssetPricing | null;
  price_cents: number | null;
  royalty_bps: number | null;
  download_count: number | null;
  usage_count: number | null;
  rating_avg: number | null;
  rating_count: number | null;
  revenue_total_wei: string | null;
  is_approved: boolean | null;
  is_active: boolean | null;
  chain_asset_id: string | null;
  fts: string | null;
  created_at: string | null;
  updated_at: string | null;
}

export interface AssetInsert {
  id?: string;
  creator_id: string;
  name: string;
  description?: string | null;
  category: AssetCategory;
  tags?: string[] | null;
  file_url: string;
  preview_url?: string | null;
  thumbnail_url?: string | null;
  file_size_bytes?: string | null;
  polygon_count?: number | null;
  file_format?: string | null;
  pricing_model?: AssetPricing | null;
  price_cents?: number | null;
  royalty_bps?: number | null;
  is_approved?: boolean | null;
  is_active?: boolean | null;
  chain_asset_id?: string | null;
  // Generated/Defaulted
  download_count?: number | null;
  usage_count?: number | null;
  rating_avg?: number | null;
  rating_count?: number | null;
  revenue_total_wei?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
  fts?: string | null;
}

export interface AssetUpdate extends Partial<AssetInsert> {}

export interface AssetPurchase {
  id: string;
  asset_id: string;
  buyer_id: string;
  price_paid_cents: number;
  tx_hash: string | null;
  rental_expires_at: string | null;
  created_at: string | null;
}

export interface AssetPurchaseInsert {
  id?: string;
  asset_id: string;
  buyer_id: string;
  price_paid_cents: number;
  tx_hash?: string | null;
  rental_expires_at?: string | null;
  created_at?: string | null;
}

export interface AssetPurchaseUpdate extends Partial<AssetPurchaseInsert> {}

export interface AssetReview {
  id: string;
  asset_id: string;
  user_id: string;
  rating: number;
  body: string | null;
  created_at: string | null;
}

export interface AssetReviewInsert {
  id?: string;
  asset_id: string;
  user_id: string;
  rating: number;
  body?: string | null;
  created_at?: string | null;
}

export interface AssetReviewUpdate extends Partial<AssetReviewInsert> {}

export interface FilmAsset {
  film_id: string;
  asset_id: string;
}

export interface FilmAssetInsert {
  film_id: string;
  asset_id: string;
}

export interface FilmAssetUpdate extends Partial<FilmAssetInsert> {}

export interface Notification {
  id: string;
  user_id: string;
  type: NotificationType;
  title: string;
  body: string | null;
  film_id: string | null;
  actor_id: string | null;
  is_read: boolean | null;
  created_at: string | null;
}

export interface NotificationInsert {
  id?: string;
  user_id: string;
  type: NotificationType;
  title: string;
  body?: string | null;
  film_id?: string | null;
  actor_id?: string | null;
  is_read?: boolean | null;
  created_at?: string | null;
}

export interface NotificationUpdate extends Partial<NotificationInsert> {}

export interface CollabSession {
  id: string;
  film_id: string;
  yjs_state: string | null;
  active_users: string[] | null;
  created_at: string | null;
  updated_at: string | null;
}

export interface CollabSessionInsert {
  id?: string;
  film_id: string;
  yjs_state?: string | null;
  active_users?: string[] | null;
  created_at?: string | null;
  updated_at?: string | null;
}

export interface CollabSessionUpdate extends Partial<CollabSessionInsert> {}

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: Profile;
        Insert: ProfileInsert;
        Update: ProfileUpdate;
      };
      series: {
        Row: Series;
        Insert: SeriesInsert;
        Update: SeriesUpdate;
      };
      films: {
        Row: Film;
        Insert: FilmInsert;
        Update: FilmUpdate;
      };
      film_creators: {
        Row: FilmCreator;
        Insert: FilmCreatorInsert;
        Update: FilmCreatorUpdate;
      };
      views: {
        Row: View;
        Insert: ViewInsert;
        Update: ViewUpdate;
      };
      donations: {
        Row: Donation;
        Insert: DonationInsert;
        Update: DonationUpdate;
      };
      comments: {
        Row: Comment;
        Insert: CommentInsert;
        Update: CommentUpdate;
      };
      likes: {
        Row: Like;
        Insert: LikeInsert;
        Update: LikeUpdate;
      };
      follows: {
        Row: Follow;
        Insert: FollowInsert;
        Update: FollowUpdate;
      };
      assets: {
        Row: Asset;
        Insert: AssetInsert;
        Update: AssetUpdate;
      };
      asset_purchases: {
        Row: AssetPurchase;
        Insert: AssetPurchaseInsert;
        Update: AssetPurchaseUpdate;
      };
      asset_reviews: {
        Row: AssetReview;
        Insert: AssetReviewInsert;
        Update: AssetReviewUpdate;
      };
      film_assets: {
        Row: FilmAsset;
        Insert: FilmAssetInsert;
        Update: FilmAssetUpdate;
      };
      notifications: {
        Row: Notification;
        Insert: NotificationInsert;
        Update: NotificationUpdate;
      };
      collab_sessions: {
        Row: CollabSession;
        Insert: CollabSessionInsert;
        Update: CollabSessionUpdate;
      };
    };
  };
}
