import { z } from 'zod';

// ============================================
// ENUMS
// ============================================

export const FilmVisibilitySchema = z.enum(['public', 'unlisted', 'private', 'draft']);
export type FilmVisibility = z.infer<typeof FilmVisibilitySchema>;

export const ContentRatingSchema = z.enum(['G', 'PG', 'T', 'M']);
export type ContentRating = z.infer<typeof ContentRatingSchema>;

export const CreatorRoleSchema = z.enum([
  'director',
  'writer',
  'animator',
  'producer',
  'sound_designer',
  'asset_creator',
  'voice_actor',
]);
export type CreatorRole = z.infer<typeof CreatorRoleSchema>;

export const AssetCategorySchema = z.enum([
  'character',
  'prop',
  'environment',
  'sprite',
  'animation_clip',
  'sound_pack',
  'template',
]);
export type AssetCategory = z.infer<typeof AssetCategorySchema>;

export const AssetPricingSchema = z.enum(['free', 'purchase', 'rental', 'royalty']);
export type AssetPricing = z.infer<typeof AssetPricingSchema>;

export const NotificationTypeSchema = z.enum([
  'donation_received',
  'comment_received',
  'like_received',
  'follow_received',
  'collab_invite',
  'collab_accepted',
  'asset_purchased',
  'asset_review',
  'fund_payout',
  'film_published',
  'episode_released',
]);
export type NotificationType = z.infer<typeof NotificationTypeSchema>;

// ============================================
// TABLES
// ============================================

// PROFILES
export const ProfileSchema = z.object({
  id: z.string().uuid(),
  display_name: z.string(),
  username: z.string(),
  avatar_url: z.string().nullable().optional(),
  bio: z.string().default(''),
  website: z.string().nullable().optional(),
  wallet_address: z.string().nullable().optional(),
  total_films: z.number().int().default(0),
  total_views: z.number().int().default(0), // BIGINT in SQL, typically JS number is fine unless massive
  total_earned_wei: z.string().default('0'), // TEXT in SQL
  follower_count: z.number().int().default(0),
  following_count: z.number().int().default(0),
  creator_weight: z.number().int().default(0),
  preferred_language: z.string().default('en'),
  preferred_role: z.string().default('director'),
  created_at: z.string().datetime().optional(),
  updated_at: z.string().datetime().optional(),
});
export type Profile = z.infer<typeof ProfileSchema>;

// SERIES
export const SeriesSchema = z.object({
  id: z.string().uuid().optional(), // Generated by default
  owner_id: z.string().uuid(),
  title: z.string(),
  description: z.string().default(''),
  thumbnail_url: z.string().nullable().optional(),
  slug: z.string(),
  genre: z.string().nullable().optional(),
  tags: z.array(z.string()).default([]),
  episode_count: z.number().int().default(0),
  subscriber_count: z.number().int().default(0),
  created_at: z.string().datetime().optional(),
  updated_at: z.string().datetime().optional(),
});
export type Series = z.infer<typeof SeriesSchema>;

// FILMS
export const FilmSchema = z.object({
  id: z.string().uuid().optional(), // Generated by default
  owner_id: z.string().uuid(),
  title: z.string(),
  description: z.string().default(''),
  slug: z.string(),
  thumbnail_url: z.string().nullable().optional(),
  video_url: z.string().nullable().optional(),
  project_json: z.record(z.unknown()).nullable().optional(), // JSONB
  duration_seconds: z.number().int().default(0),
  rating: ContentRatingSchema.default('G'),
  visibility: FilmVisibilitySchema.default('draft'),
  tags: z.array(z.string()).default([]),
  genre: z.string().nullable().optional(),
  language: z.string().default('en'),
  series_id: z.string().uuid().nullable().optional(),
  episode_number: z.number().int().nullable().optional(),
  season_number: z.number().int().default(1),
  view_count: z.number().int().default(0), // BIGINT
  like_count: z.number().int().default(0),
  comment_count: z.number().int().default(0),
  donation_total_wei: z.string().default('0'),
  avg_retention_pct: z.number().default(0), // DECIMAL
  chain_film_id: z.number().int().nullable().optional(), // BIGINT
  published_at: z.string().datetime().nullable().optional(),
  created_at: z.string().datetime().optional(),
  updated_at: z.string().datetime().optional(),
});
export type Film = z.infer<typeof FilmSchema>;

// FILM_CREATORS
export const FilmCreatorSchema = z.object({
  film_id: z.string().uuid(),
  user_id: z.string().uuid(),
  role: CreatorRoleSchema,
  revenue_share_bps: z.number().int().default(10000),
  invited_at: z.string().datetime().optional(),
  accepted_at: z.string().datetime().nullable().optional(),
});
export type FilmCreator = z.infer<typeof FilmCreatorSchema>;

// VIEWS
export const ViewSchema = z.object({
  id: z.string().uuid().optional(),
  film_id: z.string().uuid(),
  user_id: z.string().uuid().nullable().optional(),
  session_id: z.string(),
  watched_seconds: z.number().int().default(0),
  total_seconds: z.number().int(),
  // retention_pct is generated always
  source: z.string().nullable().optional(),
  device: z.string().nullable().optional(),
  country: z.string().nullable().optional(),
  created_at: z.string().datetime().optional(),
});
export type View = z.infer<typeof ViewSchema>;

// DONATIONS
export const DonationSchema = z.object({
  id: z.string().uuid().optional(),
  donor_id: z.string().uuid().nullable().optional(),
  film_id: z.string().uuid(),
  amount_wei: z.string(),
  amount_usd: z.number().nullable().optional(), // DECIMAL
  currency: z.string().default('ETH'),
  tx_hash: z.string(),
  chain: z.string().default('base'),
  block_number: z.number().int().nullable().optional(), // BIGINT
  creator_amount_wei: z.string(),
  fund_amount_wei: z.string(),
  platform_amount_wei: z.string(),
  stripe_payment_id: z.string().nullable().optional(),
  is_fiat: z.boolean().default(false),
  created_at: z.string().datetime().optional(),
});
export type Donation = z.infer<typeof DonationSchema>;

// COMMENTS
export const CommentSchema = z.object({
  id: z.string().uuid().optional(),
  film_id: z.string().uuid(),
  user_id: z.string().uuid(),
  parent_id: z.string().uuid().nullable().optional(),
  body: z.string(),
  is_edited: z.boolean().default(false),
  is_hidden: z.boolean().default(false),
  like_count: z.number().int().default(0),
  reply_count: z.number().int().default(0),
  created_at: z.string().datetime().optional(),
  updated_at: z.string().datetime().optional(),
});
export type Comment = z.infer<typeof CommentSchema>;

// LIKES
export const LikeSchema = z.object({
  film_id: z.string().uuid(),
  user_id: z.string().uuid(),
  created_at: z.string().datetime().optional(),
});
export type Like = z.infer<typeof LikeSchema>;

// FOLLOWS
export const FollowSchema = z.object({
  follower_id: z.string().uuid(),
  following_id: z.string().uuid(),
  created_at: z.string().datetime().optional(),
});
export type Follow = z.infer<typeof FollowSchema>;

// ASSETS
export const AssetSchema = z.object({
  id: z.string().uuid().optional(),
  creator_id: z.string().uuid(),
  name: z.string(),
  description: z.string().default(''),
  category: AssetCategorySchema,
  tags: z.array(z.string()).default([]),
  file_url: z.string(),
  preview_url: z.string().nullable().optional(),
  thumbnail_url: z.string().nullable().optional(),
  file_size_bytes: z.number().int().nullable().optional(), // BIGINT
  polygon_count: z.number().int().nullable().optional(),
  file_format: z.string().nullable().optional(),
  pricing_model: AssetPricingSchema.default('free'),
  price_cents: z.number().int().default(0),
  royalty_bps: z.number().int().default(0),
  download_count: z.number().int().default(0),
  usage_count: z.number().int().default(0),
  rating_avg: z.number().default(0), // DECIMAL
  rating_count: z.number().int().default(0),
  revenue_total_wei: z.string().default('0'),
  is_approved: z.boolean().default(false),
  is_active: z.boolean().default(true),
  chain_asset_id: z.number().int().nullable().optional(), // BIGINT
  created_at: z.string().datetime().optional(),
  updated_at: z.string().datetime().optional(),
});
export type Asset = z.infer<typeof AssetSchema>;

// ASSET_PURCHASES
export const AssetPurchaseSchema = z.object({
  id: z.string().uuid().optional(),
  asset_id: z.string().uuid(),
  buyer_id: z.string().uuid(),
  price_paid_cents: z.number().int(),
  tx_hash: z.string().nullable().optional(),
  rental_expires_at: z.string().datetime().nullable().optional(),
  created_at: z.string().datetime().optional(),
});
export type AssetPurchase = z.infer<typeof AssetPurchaseSchema>;

// ASSET_REVIEWS
export const AssetReviewSchema = z.object({
  id: z.string().uuid().optional(),
  asset_id: z.string().uuid(),
  user_id: z.string().uuid(),
  rating: z.number().int().min(1).max(5),
  body: z.string().default(''),
  created_at: z.string().datetime().optional(),
});
export type AssetReview = z.infer<typeof AssetReviewSchema>;

// FILM_ASSETS
export const FilmAssetSchema = z.object({
  film_id: z.string().uuid(),
  asset_id: z.string().uuid(),
});
export type FilmAsset = z.infer<typeof FilmAssetSchema>;

// NOTIFICATIONS
export const NotificationSchema = z.object({
  id: z.string().uuid().optional(),
  user_id: z.string().uuid(),
  type: NotificationTypeSchema,
  title: z.string(),
  body: z.string().nullable().optional(),
  film_id: z.string().uuid().nullable().optional(),
  actor_id: z.string().uuid().nullable().optional(),
  is_read: z.boolean().default(false),
  created_at: z.string().datetime().optional(),
});
export type Notification = z.infer<typeof NotificationSchema>;

// COLLAB_SESSIONS
export const CollabSessionSchema = z.object({
  id: z.string().uuid().optional(),
  film_id: z.string().uuid(),
  // yjs_state is BYTEA, typically represented as string (base64) or Uint8Array in JS.
  // Supabase returns bytea as hex string by default, or we might need to handle it.
  // For now, let's treat it as a string.
  yjs_state: z.string().nullable().optional(),
  active_users: z.array(z.string().uuid()).default([]),
  created_at: z.string().datetime().optional(),
  updated_at: z.string().datetime().optional(),
});
export type CollabSession = z.infer<typeof CollabSessionSchema>;
